# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20190817_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
