# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-18 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='users_app.Books'),
        ),
    ]
